name: Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v1
    - name: install build-essential
      run: sudo apt-get update >/dev/null; sudo apt-get install -y build-essential jq curl
    - name: install all pre-reqs
      run: sudo make -f package/Makefile.ubuntu install_prerequisites
    - name: build packages
      run: sudo make -f package/Makefile.ubuntu all
    - name: check packages and move locally
      run: mkdir pkg; sudo find /tmp/project -name '*.deb' -exec mv {} pkg \;
    - name: upload packages
      run: 'bash .github/scripts/upload-script "pkg/*.deb"'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
